### ISSUE TITLE
Please add LICENSE to the project (root of repo)

### ISSUE THREAD

**Issue by jonny-novikov** [Giannoudis/TimePeriodLibrary#1]
Found this library great but cannot find LICENSE file.
Have you got one? If no, I suggest MIT.

**Comment by Giannoudis** [comment]
Added the LICENSE file, it's MIT.

**Comment by Giannoudis** [comment]
Added the LICENSE file, it's MIT.

**Comment by jonny-novikov** [comment]
@Giannoudis Thank you! It's a good library!
