### ISSUE TITLE
GetRelation for empty time ranges

### ISSUE THREAD

**Issue by jnyrup** [Giannoudis/TimePeriodLibrary#10]
From the design document we see that `HasInside` implies `OverlapsWith`, which again implies `IntersectsWith`.

I've found some cases for empty time ranges, where those two invariants do not hold.

```cs
var one = new DateTime(1);
var two = new DateTime(2);
var three = new DateTime(3);

var tr12 = new TimeRange(one, two);
var tr22 = new TimeRange(two, two);
var tr23 = new TimeRange(two, three);

Assert.IsTrue(tr12.HasInside(tr22));
Assert.IsTrue(tr12.OverlapsWith(tr22)); // fails
Assert.IsTrue(tr12.IntersectsWith(tr22));

Assert.IsTrue(tr23.HasInside(tr22));
Assert.IsTrue(tr23.OverlapsWith(tr22)); // fails
Assert.IsTrue(tr23.IntersectsWith(tr22));
```

**Comment by Giannoudis** [comment]
Fixed in release v2.1.2

The first issue is not an issue, because the [End Touching](https://www.codeproject.com/KB/datetime/TimePeriod/PeriodRelations.png) scenario and should only overlap and not intersect.
```
Assert.IsTrue(tr12.OverlapsWith(tr22)); // fails
```

The second issue
```
Assert.IsTrue(tr23.OverlapsWith(tr22)); // fails
```
is fixed. see new test `OverlapsWithTest2`

many thanks @jnyrup
