### ISSUE TITLE
Nuget Package with a version compiled against .NET 4.6

### ISSUE THREAD

**Issue by Gerseras** [Giannoudis/TimePeriodLibrary#10]
Dear Mr Giannoudis,

would it be possible for you to release a new nuget package version witch is compiled against the .NET Framework Version 4.6 so that it is usable in ASP.NET 5 projects?

**Comment by Giannoudis** [comment]
There is a new NuGet Package v2.1.0 available, including bits for .NET 4.6: https://www.nuget.org/packages/TimePeriodLibrary.NET
