### ISSUE TITLE
CalendarPeriodCollector: collecting periods by day hours does not respect the limits period

### ISSUE THREAD

**Issue by Giannoudis** [Giannoudis/TimePeriodLibrary#13]
Reported by code project member [*12868655*](https://www.codeproject.com/Articles/168662/Time-Period-Library-for-NET?msg=5490911#xx5490911xx) and confirmed by code project member *jntsouza*.

----
**Problem
I was trying to collect all periods within specified Working Hours in TimeRange using DayHourRange List and CalendarPeriodCollector by collecting hours, but the hours collected contains missing hours if the TimeRange.Start is inside one of the specified Working Hours Range.

**Example**
I want to collect total working hours and periods in specified TimeRange with the following Input:
- TimeRange [04-Dec-2017 4:00:00 -> 06-Dec-2017 11:00:00] (3 days |Mon -> Wed)
- List of DayHourRange [hourFrom = 00, hourTo = 10] (same working hours for all days)

**Expected Output**
- 3 periods =
[04-Dec-2017 04:00:00 -> 04-Dec-2017 10:00:00] (6 hrs)
[05-Dec-2017 00:00:00 -> 05-Dec-2017 10:00:00] (10 hrs)
[06-Dec-2017 00:00:00 -> 06-Dec-2017 10:00:00] (10 hrs)
- Total Hours = 26 hrs

**My Code Output**
- 2 periods (first one missing)
[05-Dec-2017 00:00:00 -> 05-Dec-2017 10:00:00] (10 hrs)
[06-Dec-2017 00:00:00 -> 06-Dec-2017 10:00:00] (10 hrs)
- Total Hours = 20 hrs (6 hours missing)

**My Code**
```csharp
public TimePeriodCollection GetResourceWorkPeriods(TimeRange timeRangeLimit, int resID)
{
     List<DayHourRange> resWorkDays = LoadResWorkDays(resID);
     ///Setup Filter to collect resource working hours
     CalendarPeriodCollectorFilter workingHoursFilter = new CalendarPeriodCollectorFilter();
     foreach (DayHourRange workDay in resWorkDays)
     {
         workingHoursFilter.CollectingDayHours.Add(workDay);
     }
     TimeCalendar calendar = new TimeCalendar(new TimeCalendarConfig() { EndOffset = 
     TimeSpan.Zero, StartOffset = TimeSpan.Zero });
     CalendarPeriodCollector resCalendar = new CalendarPeriodCollector(workingHoursFilter, new 
     CalendarTimeRange(timeRangeLimit), SeekDirection.Forward, calendar);
     resCalendar.CollectHours();

     return new TimePeriodCollection(resCalendar.Periods);
}
```

**Comment by jntsouza** [comment]
@Giannoudis Perfect, the fixed worked, but this part can return sometimes null, throwing an exception
![Screenshot from 2023-08-29 15-52-45](https://github.com/Giannoudis/TimePeriodLibrary/assets/51682232/d106dc56-a095-4f10-88e1-3dcdab611726)

a simple check would make it perfect
```
if (limitedHours != null && limitedHours.Duration > TimeSpan.Zero)
```

Thanks in advance

**Comment by VenkiDevelopers** [comment]
@Giannoudis  Sorry, this commit was not supposed to be merged
https://github.com/Giannoudis/TimePeriodLibrary/pull/14/commits/b69aa57bbc08859e5eb7a7968ec93bfb4d1e881f
