### ISSUE TITLE
Release 2.1.4 is a BREAKING CHANGE

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [Giannoudis/TimePeriodLibrary#15]
Dear maintainers, 

by dropping support for .NET Framework 4.8 in release 2.1.4 several of our builds broke, due to a nuget dependency using `2.1.*`.
While it is nice to see this project is active again, this was unpleasant.

The current README still states that:

```
available for the following .NET runtime environments:

    .NET Framework from Version 3.5 or newer
    .NET Core Framework
    .NET Mono Framework
    Xamarin
    Universal Windows Platform - UWP
```

While the readme does not claim the project did ever follow semantic versioning, please consider releasing a 3.x.x version for breaking changes, thank you. 

Rel: <https://semver.org/>

**Comment by stebueh** [comment]
this change seems to have been merged accidentally, see https://github.com/Giannoudis/TimePeriodLibrary/issues/13#issuecomment-1698097136

**Comment by Giannoudis** [comment]
This was an incorrect merge. With version 2.1.5 the framework references are correct again.
