### ISSUE TITLE
Should the duration of a April be 30 days or 29.23:59:59.9999999 days?

### ISSUE THREAD

**Issue by rchamorro** [Giannoudis/TimePeriodLibrary#2]
I was playing with the Time Period Library to see if I can use it in my projects and I have found something that feels strange, at least for me.

```c#
var april = new Month(2000, YearMonth.April); // DurationDescription : "29 Days 23 Hours 59 Mins"
var aprilRange = new TimeRange(new DateTime(2000, 4, 1), new DateTime(2000, 5, 1));  // DurationDescription : "30 Days"

```
April month is different from April range and its duration is less than 30 days.

Is this what is expected?

**Comment by Giannoudis** [comment]
This is the designed behaviour, because the type Month is a calendar time period (derived from the ype  CalendarTimeRange).

See the doumentation, chapter 'Calendar Time Periods':
> Calculations with calendar periods must consider the peculiarity that the end of a time period doesn't equal the start of the following period. The following example shows the corresponding values for the hours of day between 13h and 15h:
> 
>     13:00:00.0000000 - 13:59:59.9999999
>     14:00:00.0000000 - 14:59:59.9999999
> 
> The end lies a moment before the next start, the difference between the two is at least 1 Tick = 100 nanoseconds. This is an important aspect and may not be neglected in calculations involving time periods.

```
// ----------------------------------------------------------------------
public void TimePeriodMapperSample()
{
  TimeCalendar timeCalendar = new TimeCalendar();
  CultureInfo ci = CultureInfo.InvariantCulture;

  DateTime start = new DateTime( 2011, 3, 1, 13, 0, 0 );
  DateTime end = new DateTime( 2011, 3, 1, 14, 0, 0 );

  Console.WriteLine( "Original start: {0}",
                     start.ToString( "HH:mm:ss.fffffff", ci ) );
  // > Original start: 13:00:00.0000000
  Console.WriteLine( "Original end: {0}",
                     end.ToString( "HH:mm:ss.fffffff", ci ) );
  // > Original end: 14:00:00.0000000

  Console.WriteLine( "Mapping offset start: {0}", timeCalendar.StartOffset );
  // > Mapping offset start: 00:00:00
  Console.WriteLine( "Mapping offset end: {0}", timeCalendar.EndOffset );
  // > Mapping offset end: -00:00:00.0000001

  Console.WriteLine( "Mapped start: {0}",
    timeCalendar.MapStart( start ).ToString( "HH:mm:ss.fffffff", ci ) );
  // > Mapped start: 13:00:00.0000000
  Console.WriteLine( "Mapped end: {0}",
    timeCalendar.MapEnd( end ).ToString( "HH:mm:ss.fffffff", ci ) );
  // > Mapped end: 13:59:59.9999999
} // TimePeriodMapperSample
```
