### ISSUE TITLE
Problems with IntersectPeriods

### ISSUE THREAD

**Issue by Trigun27** [Giannoudis/TimePeriodLibrary#3]
I have some problems with **IntersectPeriods**. 
I think there is some bug. The code 

```csharp
periods.Add( new TimeRange( new DateTime( 2019, 10, 19, 5, 30, 0 ), new DateTime( 2019, 10, 19, 21, 30, 0 ) ) );
periods.Add( new TimeRange( new DateTime( 2019, 10, 19, 8, 30, 0 ), new DateTime( 2019, 10, 19, 19, 30, 0 ) ) );
periods.Add( new TimeRange( new DateTime( 2019, 10, 19, 14, 30, 0 ), new DateTime( 2019, 10, 19, 15, 30, 0  ) ) );
periods.Add( new TimeRange( new DateTime( 2019, 10, 19, 16, 30, 0 ), new DateTime( 2019, 10, 19, 17, 0, 0 ) ) );
var periodIntersector =new TimePeriodIntersector<TimeRange>();
var intersectedPeriods = periodIntersector.IntersectPeriods( periods );
```
here is the photo that represents time intervals
![photo_2019-10-18_17-18-15](https://user-images.githubusercontent.com/5838703/67102035-78de4b00-f1cb-11e9-93f3-0929c753e882.jpg)

I expected that the result would be two interval (like the line 4), 
but collection has only one time period from 2019.10.19 8:30 -> 2019.10.19 19:30 (like the line 2)

**Comment by Giannoudis** [comment]
If you wanna test if EF or GJ is intersected by AB and CD, the you can add AB and CD to a time period collection and use the method periods.IntersectsWith(EF) and periods.IntersectsWith(GJ).

In case you should test if a specific amount of overlapping periods are present, you should use the timeline approach.

**Comment by Trigun27** [comment]
Why after adding EF and GJ to **TimePeriodCollection** **TimePeriodIntersector** stops working. For these time periods, it was logical to get two resulting time periods, as on line 4, because It is in these segments there is the intersection of time for all segments.

Tried to use **TimePeriodIntersector** to find users busy time.
But for this data, the result is CD line

**Comment by Trigun27** [comment]
Aaaa never mind. I have read the docs and uderstood the idea of **TimePeriodIntersector**. It finds the maximum intersection. 
Checking my(new) intersection method with TimeLineCollection.
