### ISSUE TITLE
load collections of time blocks, time series

### ISSUE THREAD

**Issue by mach37** [Giannoudis/TimePeriodLibrary#4]
Hi, I am switching over some attendance and reservations classes from the bcl .net to your  TimePeriodLibrary 👍  (my next move is to use an opensource time series DB, so CRUD operations are well aligned with the time lib)

Now, I am stuck with loading collections of blocks of time. I want to work with _collections of < timeworked>_. I see you have some options, I picked this ITimePeriodCollection - is this correct, for instance if I wanted to show this in a DatatGrid/Table time card, startDate + hours worked?

- [ ] 1. **Using the **TimePeriodLibrary**, how do I model these user worked timeblocks effectively?**
Or, how do I model/represent a startDate+Duration?

 2.  Can I build a custom time card block like this??
```
Class CustomTimePeriod {
User userId,  
Date? startDate, 
String frequencyWeeklyBiWeeklyMonthly, // what schedule is he on?
ITimePeriodCollection <StartDate+DurationHoursWorked> WorkDays)  // if biweekly, then get 14 working slots
//int ProjectId; 
}
```

 3.  **I want to perform basic CRUD with your lib as a timeseries of working hours.**
For e.g. in a user Time - Card I want to `GET `and `SAVE the time cards.
`
```
// **Get** the list of hoursWorked for this payPeriod
ActionResult GETUserTimeCard(
User userId,  
Date? startDate, 
String frequencyWeeklyBiWeeklyMonthly, // what schedule is he on?
)  // if biweekly, then get 14 working slots
{   ... 
CustomTimeSeriesWorkDays = TimeBy(userId, startDate, frequencyWeeklyBiWeeklyMonthly);
viewbag.timeworked =  new ITimePeriodCollection <StartDate+DurationHoursWorked>(CustomTimeSeriesWorkDays); //??
return view();  ..  }
```

 4. **Save/Edit**
```
//Save the list of hoursWorked for this payPeriod
ActionResult SAVEUserTimeCard(
User userId,  
Date? startDate, 
String frequencyWeeklyBiWeeklyMonthly, // what schedule is he on?
ITimePeriodCollection <StartDate+DurationHoursWorked> WorkDays)  // if biweekly, then get 14 working slots
) 
{ .. }
```

any help would be greatly appreciated!

**Comment by Giannoudis** [comment]
The class `TimeBlock` defines a time period based on a time and a duration (example on [CodeProject](https://www.codeproject.com/Articles/168662/Time-Period-Library-for-NET?msg=4380675#xx4380675xx)).
