### ISSUE TITLE
support for .net core

### ISSUE THREAD

**Issue by nrubiano** [Giannoudis/TimePeriodLibrary#5]
Hi, i want to ask you if are you planning to migrate this library to run on .net core?

thanks

**Comment by Giannoudis** [comment]
Thanks for the request. I'm currently adding support for net core, but I have some issues with the unit tests. I will keep you on track.

Cheers
Jani

**Comment by nxtayi** [comment]
+1

**Comment by raaraya** [comment]
++1. This is a killer utility library. Better documentation would be helpful too, but, not top priority as having this available on .Net Core

**Comment by Giannoudis** [comment]
There is a new version 2.1.0 available, including support for .NET Core.
@raaraya: there is some documentation (docu/TimePeriod_en.doc/pdf) and online on [CodeProject](https://www.codeproject.com/Articles/168662/Time-Period-Library-for-NET) available. Check also the cumminy examples (TimePeriodDemo/CommunitySamples.cs).
