### ISSUE TITLE
Divide a TimeRange in contiguous equal TimeRanges ?

### ISSUE THREAD

**Issue by Larry57** [Giannoudis/TimePeriodLibrary#7]
To be able to plot a huge set of data points between a start date and an end date, I am performing data decimation.

So, to keep an accurate curve shape, I need to subdivise the TimeRange (from start to end) by an amount of pixels to obtain equally sized contiguous TimeRanges, and performs a decimation algorithm with all the points in every TimeRanges.

I am looking for something like a "/" operator or a TimePeriodDivider to split the root TimeRange to many TimeRanges, but I have not found anything yet about how to proceed.

Is this feature implemented ?

Thank you for your help.

**Comment by Giannoudis** [comment]
You can use the duration of a period and divide it.
```csharp
public void TimeDivide()
{
    var timePeriod = new Month(2023, YearMonth.August);

    // half day
    int partCount = 62;
    var partSize = (timePeriod.Duration.Ticks / partCount) + 1;
    for (var i = 0; i < partCount; i++)
    {
        var start = timePeriod.Start.AddTicks(i * partSize);
        var end = start.AddTicks(partSize - 1);
        var timeRange = new TimeRange(start, end);
        Console.WriteLine($"Part {i + 1}: {timeRange}");
    }
}
```

**Comment by Giannoudis** [comment]
See previous post.
