### ISSUE TITLE
ToString() formatting

### ISSUE THREAD

**Issue by MarijnPessers** [Giannoudis/TimePeriodLibrary#8]
I am using the ToString() method to get the date in a string to be useable by an API.
I would like to be able to pass a culture to the ToString() method so we can control the way the result looks like.

**Comment by Giannoudis** [comment]
You can use the `TimeFormatter.GetDateTime()` to format a date.
```csharp
public void ToStringCultureTest()
{
    var start = new DateTime(2013, 12, 15);
    var culture = new CultureInfo("en-US");
    var enUsFormatter = new TimeFormatter(culture);
    Assert.Equal(start.ToString(culture), enUsFormatter.GetDateTime(start) );
} // ToStringCultureTest
```
